### ISSUE TITLE
README.md missing in archive

### ISSUE THREAD

**Issue by marscher** [eric-wieser/numpy_ringbuffer#1]
setup.py complains when doing the pypi install. You have to provide a MANIFEST.in file, which contains README.md to automatically ship it

**Comment by stuaxo** [comment]
https://github.com/eric-wieser/numpy_ringbuffer/pull/3

**Comment by eric-wieser** [comment]
Fixed in £3

**Comment by marscher** [comment]
thank you!

**Comment by eric-wieser** [comment]
(and v0.2.1 on PyPI)

**Comment by stuaxo** [comment]
Awesome, cheers :)
