### ISSUE TITLE
DepretiationWarning

### ISSUE THREAD

**Issue by vulogov** [eric-wieser/numpy_ringbuffer#12]
`/Users/gandalf/Documents/Src/core.F/venv/lib/python3.7/site-packages/numpy_ringbuffer/__init__.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Sequence`

**Comment by eric-wieser** [comment]
FIxed in v0.2.2
